#!/usr/bin/env sh

set -eu

if [ -z "${APP_SERVER_CMD:-}" ]; then
  echo "ERROR: APP_SERVER_CMD is required (the command to start your app-server)." >&2
  exit 2
fi

APP_HOME_DIR="${APP_HOME:-/root/.argus}"
APP_WORKSPACE_DIR="${APP_WORKSPACE:-/workspace}"

mkdir -p "$APP_HOME_DIR" "$APP_WORKSPACE_DIR"

TEMPLATE_DIR="/app/docs/templates"

write_workspace_file_from_template() {
  src="$1"
  dst="$2"
  tmp="${dst}.tmp.$$"

  if [ -f "$src" ]; then
    # Strip YAML front matter if present (--- ... --- at top).
    awk 'NR==1{if($0=="---"){fm=1; next}} fm==1{if($0=="---"){fm=0; next} next} {print}' "$src" > "$tmp"
  else
    printf '# %s\n' "$(basename "$dst")" > "$tmp"
  fi

  if [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then
    rm -f "$tmp"
    return 0
  fi

  mv -f "$tmp" "$dst"
}

bootstrap_workspace_file() {
  src="$1"
  dst="$2"

  if [ -e "$dst" ]; then
    return 0
  fi

  write_workspace_file_from_template "$src" "$dst"
}

sync_workspace_file() {
  src="$1"
  dst="$2"

  write_workspace_file_from_template "$src" "$dst"
}

# Sync AGENTS.md from the template on every start; bootstrap the rest if missing.
sync_workspace_file "$TEMPLATE_DIR/AGENTS.default.md" "$APP_WORKSPACE_DIR/AGENTS.md"
bootstrap_workspace_file "$TEMPLATE_DIR/SOUL.md" "$APP_WORKSPACE_DIR/SOUL.md"
bootstrap_workspace_file "$TEMPLATE_DIR/USER.md" "$APP_WORKSPACE_DIR/USER.md"
bootstrap_workspace_file "$TEMPLATE_DIR/HEARTBEAT.md" "$APP_WORKSPACE_DIR/HEARTBEAT.md"

# Scope Codex state (threads/history, config, etc.) to the workspace by default.
# This avoids cross-session leakage when multiple runtimes share the same host.
CODEX_HOME_DIR="${CODEX_HOME:-$APP_WORKSPACE_DIR/.codex}"
export CODEX_HOME="$CODEX_HOME_DIR"
ARGUS_CODEX_MODEL_FILE="${ARGUS_CODEX_MODEL_FILE:-$CODEX_HOME_DIR/argus-agent-model}"

export HOME="$APP_HOME_DIR"

normalize_argus_codex_model() {
  value="$(printf '%s' "$1" | tr -d '\r\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  if [ -z "$value" ]; then
    printf '%s' "gpt-5.4"
    return 0
  fi
  if [ "${#value}" -gt 128 ]; then
    printf '%s' "gpt-5.4"
    return 0
  fi
  case "$value" in
    *[!A-Za-z0-9._:/+-]*)
      printf '%s' "gpt-5.4"
      ;;
    *)
      printf '%s' "$value"
      ;;
  esac
}

CODEX_MODEL_RAW="${ARGUS_CODEX_MODEL:-}"
if [ -f "$ARGUS_CODEX_MODEL_FILE" ]; then
  CODEX_MODEL_RAW="$(cat "$ARGUS_CODEX_MODEL_FILE")"
fi
CODEX_MODEL="$(normalize_argus_codex_model "$CODEX_MODEL_RAW")"

# Seed Codex config in $CODEX_HOME/config.toml (no secrets).
# Note: this overwrites any existing file.
if command -v codex >/dev/null 2>&1; then
  mkdir -p "$CODEX_HOME_DIR"
  printf '%s\n' "$CODEX_MODEL" > "$ARGUS_CODEX_MODEL_FILE"

  tmp_cfg="$(mktemp "$CODEX_HOME_DIR/config.toml.XXXXXX")"

  cat > "$tmp_cfg" <<EOF
# Generated by Argus runtime (no secrets).
model = "$CODEX_MODEL"
model_reasoning_effort = "high"
EOF

  # NOTE: In TOML, keys defined after a table header (e.g. [mcp_servers.argus])
  # belong to that table until another table header appears. Keep top-level keys
  # (like model_provider) above any table blocks.
  if [ -n "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL:-}" ]; then
    cat >> "$tmp_cfg" <<EOF

model_provider = "argus-openai-proxy"
EOF
  fi

  cat >> "$tmp_cfg" <<EOF

[mcp_servers.argus]
url = "${ARGUS_CODEX_MCP_URL:-http://gateway:8080/mcp}"
bearer_token_env_var = "ARGUS_MCP_TOKEN"
EOF

  if [ -n "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL:-}" ]; then
    cat >> "$tmp_cfg" <<EOF

[model_providers.argus-openai-proxy]
name = "Argus OpenAI Proxy"
base_url = "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL}"
wire_api = "responses"
env_key = "ARGUS_OPENAI_TOKEN"
requires_openai_auth = false
EOF
  fi

  mv -f "$tmp_cfg" "$CODEX_HOME_DIR/config.toml"
fi

cd "$APP_WORKSPACE_DIR"

exec sh -lc "$APP_SERVER_CMD"
