#!/usr/bin/env sh

set -eu

if [ -z "${APP_SERVER_CMD:-}" ]; then
  echo "ERROR: APP_SERVER_CMD is required (the command to start your app-server)." >&2
  exit 2
fi

APP_HOME_DIR="${APP_HOME:-/root/.argus}"
APP_WORKSPACE_DIR="${APP_WORKSPACE:-$APP_HOME_DIR/workspace}"

mkdir -p "$APP_HOME_DIR" "$APP_WORKSPACE_DIR"

TEMPLATE_DIR="/app/docs/templates"

bootstrap_workspace_file() {
  src="$1"
  dst="$2"

  if [ -e "$dst" ]; then
    return 0
  fi

  if [ -f "$src" ]; then
    # Strip YAML front matter if present (--- ... --- at top).
    awk 'NR==1{if($0=="---"){fm=1; next}} fm==1{if($0=="---"){fm=0; next} next} {print}' "$src" > "$dst"
  else
    printf '# %s\n' "$(basename "$dst")" > "$dst"
  fi
}

# Bootstrap "OpenClaw-style" workspace context files (do not overwrite if already present).
bootstrap_workspace_file "$TEMPLATE_DIR/SOUL.md" "$APP_WORKSPACE_DIR/SOUL.md"
bootstrap_workspace_file "$TEMPLATE_DIR/USER.md" "$APP_WORKSPACE_DIR/USER.md"
bootstrap_workspace_file "$TEMPLATE_DIR/AGENTS.default.md" "$APP_WORKSPACE_DIR/AGENTS.md"
bootstrap_workspace_file "$TEMPLATE_DIR/HEARTBEAT.md" "$APP_WORKSPACE_DIR/HEARTBEAT.md"

export HOME="$APP_HOME_DIR"

# Seed Codex config in $CODEX_HOME/config.toml (no secrets).
# Note: this overwrites any existing file.
if command -v codex >/dev/null 2>&1; then
  CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
  mkdir -p "$CODEX_HOME_DIR"

  cat > "$CODEX_HOME_DIR/config.toml" <<EOF
# Generated by Argus runtime (no secrets).
model = "gpt-5.2"
model_reasoning_effort = "high"

[mcp_servers.argus]
url = "${ARGUS_CODEX_MCP_URL:-http://gateway:8080/mcp}"
bearer_token_env_var = "ARGUS_MCP_TOKEN"
EOF

  if [ -n "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL:-}" ]; then
    cat >> "$CODEX_HOME_DIR/config.toml" <<EOF

model_provider = "argus-openai-proxy"

[model_providers.argus-openai-proxy]
name = "Argus OpenAI Proxy"
base_url = "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL}"
wire_api = "responses"
env_key = "ARGUS_OPENAI_TOKEN"
requires_openai_auth = false
EOF
  fi
fi

cd "$APP_WORKSPACE_DIR"

exec sh -lc "$APP_SERVER_CMD"
