#!/usr/bin/env sh

set -eu

if [ -z "${APP_SERVER_CMD:-}" ]; then
  echo "ERROR: APP_SERVER_CMD is required (the command to start your app-server)." >&2
  exit 2
fi

APP_HOME_DIR="${APP_HOME:-/root/.argus}"
APP_WORKSPACE_DIR="${APP_WORKSPACE:-/workspace}"

mkdir -p "$APP_HOME_DIR" "$APP_WORKSPACE_DIR"

TEMPLATE_DIR="/app/docs/templates"

bootstrap_workspace_file() {
  src="$1"
  dst="$2"

  if [ -e "$dst" ]; then
    return 0
  fi

  if [ -f "$src" ]; then
    # Strip YAML front matter if present (--- ... --- at top).
    awk 'NR==1{if($0=="---"){fm=1; next}} fm==1{if($0=="---"){fm=0; next} next} {print}' "$src" > "$dst"
  else
    printf '# %s\n' "$(basename "$dst")" > "$dst"
  fi
}

# Bootstrap "OpenClaw-style" workspace context files (do not overwrite if already present).
bootstrap_workspace_file "$TEMPLATE_DIR/SOUL.md" "$APP_WORKSPACE_DIR/SOUL.md"
bootstrap_workspace_file "$TEMPLATE_DIR/USER.md" "$APP_WORKSPACE_DIR/USER.md"
bootstrap_workspace_file "$TEMPLATE_DIR/AGENTS.default.md" "$APP_WORKSPACE_DIR/AGENTS.md"
bootstrap_workspace_file "$TEMPLATE_DIR/HEARTBEAT.md" "$APP_WORKSPACE_DIR/HEARTBEAT.md"

# Scope Codex state (threads/history, config, etc.) to the workspace by default.
# This avoids cross-session leakage when multiple runtimes share the same host.
CODEX_HOME_DIR="${CODEX_HOME:-$APP_WORKSPACE_DIR/.codex}"
export CODEX_HOME="$CODEX_HOME_DIR"

export HOME="$APP_HOME_DIR"

# Seed Codex config in $CODEX_HOME/config.toml (no secrets).
# Note: this overwrites any existing file.
if command -v codex >/dev/null 2>&1; then
  mkdir -p "$CODEX_HOME_DIR"

  tmp_cfg="$(mktemp "$CODEX_HOME_DIR/config.toml.XXXXXX")"

  cat > "$tmp_cfg" <<EOF
# Generated by Argus runtime (no secrets).
model = "gpt-5.2"
model_reasoning_effort = "high"
EOF

  # NOTE: In TOML, keys defined after a table header (e.g. [mcp_servers.argus])
  # belong to that table until another table header appears. Keep top-level keys
  # (like model_provider) above any table blocks.
  if [ -n "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL:-}" ]; then
    cat >> "$tmp_cfg" <<EOF

model_provider = "argus-openai-proxy"
EOF
  fi

  cat >> "$tmp_cfg" <<EOF

[mcp_servers.argus]
url = "${ARGUS_CODEX_MCP_URL:-http://gateway:8080/mcp}"
bearer_token_env_var = "ARGUS_MCP_TOKEN"
EOF

  if [ -n "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL:-}" ]; then
    cat >> "$tmp_cfg" <<EOF

[model_providers.argus-openai-proxy]
name = "Argus OpenAI Proxy"
base_url = "${ARGUS_CODEX_OPENAI_PROXY_BASE_URL}"
wire_api = "responses"
env_key = "ARGUS_OPENAI_TOKEN"
requires_openai_auth = false
EOF
  fi

  mv -f "$tmp_cfg" "$CODEX_HOME_DIR/config.toml"
fi

cd "$APP_WORKSPACE_DIR"

exec sh -lc "$APP_SERVER_CMD"
